### ISSUE TITLE
Why not keeping easyrdf/easyrdf as package name?

### ISSUE THREAD

**Issue by claudiu-cristea** [sweetrdf/easyrdf#19]
I see the package name is now `sweetrdf/easyrdf`, see https://github.com/sweetrdf/easyrdf/blob/master/composer.json#L2. This is an issue for projects having dependencies that require themselves the original  `easyrdf/easyrdf`. For such projects it's hard to convince the dependency maintainer to update their dependency from `easyrdf/easyrdf` to `sweetrdf/easyrdf`.

Proposal:
1. EITHER, use the original name `easyrdf/easyrdf` in `composer.json`. In that case such projects can add https://github.com/sweetrdf/easyrdf as repository, in their composer.json `repositories` section, and the code will be fetched from https://github.com/sweetrdf/easyrdf.
2. OR, add a [`replace` property](https://getcomposer.org/doc/04-schema.md#replace) in `composer.json`. Then such projects can require directly `sweetrdf/easyrdf`, overriding the requirement to `easyrdf/easyrdf` coming from the dependency. A nice explanation on how `replace` works https://www.darwinbiler.com/how-does-the-replace-property-work-in-composer/

If none of this will be implemented, I'll need to fork https://github.com/sweetrdf/easyrdf and solve the issue in one way or another.

**Comment by k00ni** [comment]
Hello @claudiu-cristea, I never though about this to be an issue, but I am open for either way. If I understand your proposals correct, the second one seems to be the easiest to be implemented. Would you mind making a pull request?

_Off topic:_ I appreciate your interest in my fork. My goal back than (https://github.com/easyrdf/easyrdf/issues/320, in 2020) as well as currently is to provide a working version of EasyRdf. If that helps more users to migrate the better!

CC @zozlak

**Comment by k00ni** [comment]
@claudiu-cristea, does pull request https://github.com/sweetrdf/easyrdf/pull/20 reflect the changes of your second proposal?

**Comment by zozlak** [comment]
The first solution won't work with packagist.org as it requires package names to be unique (which makes a lot of sense). And even if it would be technicallyy possible it would create a lot of tension between Konrad and Nicholas Humfrey and we definitely don't want that.

The second solution seems fine though and the pull request prepared by @k00ni looks fine at the  glance.

**Comment by claudiu-cristea** [comment]
@zozlak a fork can have the same name as the main project. This is not a point. I also have a fork with the same name that I'm using exactly for the same reason why I've opened this issue.

But I also tend to go with the PR solution. However, I didn't find yet time to test it. Will do in the next couple of days

**Comment by k00ni** [comment]
> I didn't find yet time to test it. Will do in the next couple of days

Looking forward to it. I hope you will like this fork and give it a shoot. Let me know when I can help out.
