### ISSUE TITLE
Allow hyphen in prefix name

### ISSUE THREAD

**Issue by lecoqlibre** [sweetrdf/easyrdf#32]
I'm not able to use a prefix registered through `\EasyRdf\RdfNamespace::set("prefix-with-hyphen", "https://uri.com")`.

The prefix `prefix-with-hyphen` is well registered as a new namespace as a call to `\EasyRdf\RdfNamespace::namespaces()` confirms it.

But I can't retrieve the prefix because the `\EasyRdf\RdfNamespace::get("prefix-with-hyphen")` does not allow me, complaining with "$prefix should only contain alpha-numeric characters".

The check is made in the [RdfNamespace.php](https://github.com/sweetrdf/easyrdf/blob/master/lib/RdfNamespace.php#L158-L159) with:
```
if (preg_match('/\W/', $prefix)) {
     throw new \InvalidArgumentException('$prefix should only contain alpha-numeric characters');
```

Hyphen are allowed in a prefix name, right? See the [JSON-LD spec](https://www.w3.org/TR/json-ld/#terms).

**Comment by k00ni** [comment]
Your JSON-LD reference is a bit worded in general terms. It is also JSON-LD specific and I am not sure on which specification this implementation was based on. Class RdfNamespace is used in [various places](https://github.com/search?q=repo%3Asweetrdf%2Feasyrdf%20RdfNamespace&type=code), so it must conform with all serializations (RDF/XML, RDF/Turtle, JSON-LD, SPARQL, ...). In a quick search I've found the following reference in the SPARQL specification about allowed characters in a prefix: https://www.w3.org/TR/rdf-sparql-query/#rPN_CHARS_BASE

Besides a-z, there are others in Unicode. Maybe one of them represents a hyphen? What helps would be a list of links to all specifications and their respective requirements to prefix characters. Could you help me out here @lecoqlibre?

**Comment by lecoqlibre** [comment]
Why do the constraints in the `\EasyRdf\RdfNamespace::get` method differ from the one in the `\EasyRdf\RdfNamespace::set` method?

Should not these constraints be the same? The "get constraint" should be replaced with the constraint defined in the set method, don't you think?

**Comment by k00ni** [comment]
That sounds reasonable. I plan to propose a change for `get` and `set` functions, although my time is spare currently. But I am open for suggestions.

**Comment by k00ni** [comment]
@lecoqlibre please checkout #33 to see if it fits your needs.

**Comment by lecoqlibre** [comment]
Thank you @k00ni , it's better but there is still an issue with the `RdfNamespace::expand` method line [431] and [436]. The hyphen is not allowed so the method `Resource::type` return null when a prefix with an hyphen is used.

In `RdfNamespace`, line [431] should be:
```
} elseif (preg_match('/^([\w\-]+?):([\w\-]+)$/', $shortUri, $matches)) {
```

In `RdfNamespace`, I assume that line [436] should also be :
```
} elseif (preg_match('/^([\w\-]+)$/', $shortUri) && isset(self::$default)) {
```

(I added the `\-` in `[\w\-]`).

[431]: https://github.com/sweetrdf/easyrdf/blob/703a52a1aa6faa0a58f10dbe31b0fba75854c990/lib/RdfNamespace.php#L431
[436]: https://github.com/sweetrdf/easyrdf/blob/703a52a1aa6faa0a58f10dbe31b0fba75854c990/lib/RdfNamespace.php#L436

**Comment by k00ni** [comment]
I adapted `RdfNamespace::expand` using your suggestions: https://github.com/sweetrdf/easyrdf/pull/33/files#diff-0075e094016772a5abd954c3800bb43ef89fdc0786a4c3a32b67d3a50a4eb63cL418

There are also a few new tests covering hyphen usage: https://github.com/sweetrdf/easyrdf/pull/33/files#diff-72c1f0403f0841ffb42f62840f0be8f113e52cb96167a033d1c6d27bc4a1a3f1R665

I hope everything is covered now, please check if that works for you. Thanks!

**Comment by lecoqlibre** [comment]
Yes it works now, thank you @k00ni !

Hope you will be able to release a new version in the next days so we don't need a patch anymore ;)

**Comment by k00ni** [comment]
I travel in the next days, so you can expect a release after 12th September.

**Comment by k00ni** [comment]
@lecoqlibre a new release is available.
